AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation CI/CD Pipeline using CodeCommit, CodeBuild, and CodePipeline

Parameters:
  CodeCommitRepoName:
    Type: String
  ArtifactBucketName:
    Type: String
  PipelineRoleArn:
    Type: String

Resources:
  ValidateProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-validate"
      ServiceRole: !Ref PipelineRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: CFN_LINT_VERSION
            Value: "0.84.0"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              runtime-versions:
                python: 3.9
              commands:
                - pip install cfn-lint==${CFN_LINT_VERSION}
            build:
              commands:
                - echo "Validating template.yaml"
                - cfn-lint template.yaml
                - aws cloudformation validate-template --template-body file://template.yaml

          cache:
            paths:
              - '/root/.cache/pip/**/*'

  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Ref PipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: FetchSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref CodeCommitRepoName
                BranchName: main

        - Name: Validate
          Actions:
            - Name: ValidateTemplates
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref ValidateProject

        - Name: ManualApproval
          Actions:
            - Name: ApproveChangeSet
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration:
                CustomData: "Manual approval required before deployment"

        - Name: Deploy
          Actions:
            - Name: DeployTemplate
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: deployed-cfn-stack
                TemplatePath: SourceOutput::template.yaml
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
